import { FileText, ChevronRight, Clock, Sparkles, Calendar, Pencil } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { useBlogPosts } from '@/hooks/useBooks';
import { formatDate, truncateText } from '@/lib/utils';
import { useAuth } from '@/components/AuthProvider';
import { useAppNav } from '@/App';
import { useTranslation } from '@/lib/i18n';
import { motion } from 'framer-motion';

export function Blog() {
  const { posts, loading } = useBlogPosts(4);
  const { isAdmin } = useAuth();
  const { navigate } = useAppNav();
  const { t } = useTranslation();

  const getGeneratedByIcon = (generatedBy?: string) => {
    switch (generatedBy) {
      case 'ai':
        return <Sparkles className="h-3 w-3" />;
      case 'cron':
        return <Clock className="h-3 w-3" />;
      default:
        return <FileText className="h-3 w-3" />;
    }
  };

  const getGeneratedByLabel = (generatedBy?: string) => {
    switch (generatedBy) {
      case 'ai':
        return t('blog.aiGenerated');
      case 'cron':
        return t('blog.autoGenerated');
      default:
        return t('blog.editorial');
    }
  };

  return (
    <section id="blog" className="py-12 sm:py-16 md:py-24">
      <div className="container mx-auto px-4">
        {/* Section Header */}
        <motion.div 
          className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-10"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Badge variant="default" className="bg-purple-500">
                <Sparkles className="w-3 h-3 mr-1" />
                {t('blog.aiPowered')}
              </Badge>
            </div>
            <h2 className="text-3xl md:text-4xl font-bold font-serif flex items-center gap-3">
              <FileText className="h-8 w-8 text-primary" />
              {t('sections.blog')}
            </h2>
            <p className="text-muted-foreground max-w-xl">
              {t('blog.subtitle')}
            </p>
          </div>
          <Button variant="outline" asChild>
            <Link to="/blog">
              {t('blog.viewAllPosts')}
              <ChevronRight className="ml-2 h-4 w-4" />
            </Link>
          </Button>
        </motion.div>

        {/* Blog Grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
          {loading ? (
            Array.from({ length: 3 }).map((_, i) => (
              <Card key={i} className="h-96">
                <div className="animate-pulse">
                  <div className="h-48 bg-muted" />
                  <CardContent className="p-6 space-y-4">
                    <div className="h-4 w-20 bg-muted rounded" />
                    <div className="h-6 w-full bg-muted rounded" />
                    <div className="h-4 w-3/4 bg-muted rounded" />
                  </CardContent>
                </div>
              </Card>
            ))
          ) : (
            posts.map((post, index) => (
              <motion.div
                key={post.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.3, delay: index * 0.1 }}
              >
                <Card className="group overflow-hidden transition-all duration-300 hover:shadow-lg hover:-translate-y-1 h-full flex flex-col relative">
                  {isAdmin && (
                    <Button
                      size="icon"
                      variant="ghost"
                      className="absolute right-4 top-4 z-10 h-8 w-8 rounded-full bg-orange-500/90 text-white opacity-0 transition-opacity duration-300 group-hover:opacity-100"
                      onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        navigate({ type: 'admin', page: 'blog' });
                      }}
                      title="Edit in admin"
                    >
                      <Pencil className="h-3.5 w-3.5" />
                    </Button>
                  )}
                  <Link to={`/blog/${post.slug}`} className="flex flex-col flex-1">
                  <div className="relative h-48 overflow-hidden">
                    <img
                      src={post.featuredImage}
                      alt={post.title}
                      className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                    />
                    <div className="absolute top-4 left-4">
                      <Badge variant="secondary" className="bg-white/90 text-foreground">
                        {getGeneratedByIcon(post.generatedBy)}
                        <span className="ml-1">{getGeneratedByLabel(post.generatedBy)}</span>
                      </Badge>
                    </div>
                  </div>
                  <CardContent className="p-6 flex flex-col flex-1">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground mb-3">
                      <Calendar className="h-4 w-4" />
                      {post.publishedAt && formatDate(post.publishedAt)}
                    </div>
                    <h3 className="text-xl font-bold mb-2 line-clamp-2 group-hover:text-primary transition-colors">
                      {post.title}
                    </h3>
                    <p className="text-muted-foreground line-clamp-3 flex-1">
                      {post.excerpt || truncateText(post.content, 150)}
                    </p>
                    <div className="flex items-center justify-between mt-4 pt-4 border-t">
                      <span className="text-sm text-muted-foreground">
                        {post.featuredBookIds.length} {t('blog.booksFeatured')}
                      </span>
                      <span className="text-sm font-medium text-primary group-hover:underline flex items-center">
                        {t('book.readMore')}
                        <ChevronRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-1" />
                      </span>
                    </div>
                  </CardContent>
                  </Link>
                </Card>
              </motion.div>
            ))
          )}
        </div>

        {/* Auto-Generation Info */}
        <motion.div 
          className="mt-12 p-6 bg-gradient-to-r from-purple-500/10 to-primary/10 rounded-xl border border-purple-500/20"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-full bg-purple-500/20">
                <Sparkles className="h-6 w-6 text-purple-600" />
              </div>
              <div>
                <h4 className="font-semibold">{t('blog.aiWeekly')}</h4>
                <p className="text-sm text-muted-foreground">
                  {t('blog.aiWeeklyDesc')}
                </p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <div className="text-center">
                <p className="text-2xl font-bold">{posts.length > 0 ? `${posts.length}+` : '...'}</p>
                <p className="text-xs text-muted-foreground">{t('blog.articles')}</p>
              </div>
              <div className="text-center">
                <p className="text-2xl font-bold">{t('blog.weekly')}</p>
                <p className="text-xs text-muted-foreground">{t('blog.newContent')}</p>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
